In [122]:
import numpy as np

### Numpy is used to satistical operation on array

In [123]:
l = [1,2,444,86,23,654]

In [124]:
np.array(l)

array([  1,   2, 444,  86,  23, 654])

In [125]:
l1 = [1,43,62,"naren",23.43,'@',True]

In [126]:
np.array(l1)

array(['1', '43', '62', 'naren', '23.43', '@', 'True'], dtype='<U32')

In [127]:
np.array([[3,5,1,3],[1,6,7,2],[5,6,82,34]])

array([[ 3,  5,  1,  3],
       [ 1,  6,  7,  2],
       [ 5,  6, 82, 34]])

In [128]:
a1 = np.array(l1)
a2 = np.array([[3,5,1,3],[1,6,7,2]])
a3 = np.array([[3,5,1,3],[1,6,7,2],[5,6,82,34]])
a4 = np.array([[[3,5,1,3],[1,6,7,2],[5,6,82,34]]])

In [129]:
print(a1,'\ndim = ',a1.ndim)

['1' '43' '62' 'naren' '23.43' '@' 'True'] 
dim =  1


In [130]:
print(a2,'\ndim = ',a2.ndim)

[[3 5 1 3]
 [1 6 7 2]] 
dim =  2


In [131]:
print(a3,'\ndim = ',a3.ndim)

[[ 3  5  1  3]
 [ 1  6  7  2]
 [ 5  6 82 34]] 
dim =  2


In [132]:
print(a4,'\ndim = ',a4.ndim)

[[[ 3  5  1  3]
  [ 1  6  7  2]
  [ 5  6 82 34]]] 
dim =  3


In [133]:
a1.size

7

In [134]:
a2.size

8

In [135]:
a1.shape

(7,)

In [136]:
a2.shape

(2, 4)

In [137]:
a3.shape

(3, 4)

In [138]:
a4.shape

(1, 3, 4)

In [139]:
np.random.randint(2,40,(2,3,4))

array([[[20, 19,  9,  4],
        [ 2,  8, 26, 19],
        [ 4, 33, 13,  4]],

       [[ 5, 25, 11,  2],
        [31, 10, 14,  2],
        [19, 38,  7, 10]]])

In [140]:
np.random.rand(2,4)

array([[0.86738542, 0.72869084, 0.98748493, 0.44887164],
       [0.05291913, 0.55854705, 0.49432211, 0.71583362]])

In [141]:
np.random.randn(2,4)
# mean of a column will be zero
# gives normal distribution data

array([[ 1.64706516, -1.84635876, -0.71844173, -0.51092836],
       [ 0.59835794,  0.29136114, -1.98284451, -1.30754059]])

In [142]:
a5 = np.random.randn(2,4)
a5.reshape(4,2)

array([[-0.31564177, -1.40582767],
       [ 0.1290978 ,  2.59538928],
       [-0.25646788, -1.45501661],
       [-1.79622745, -1.28522373]])

In [143]:
a5.reshape(4,-1)
# when negative number is given, it will automatically calculate the column according to the row number given

array([[-0.31564177, -1.40582767],
       [ 0.1290978 ,  2.59538928],
       [-0.25646788, -1.45501661],
       [-1.79622745, -1.28522373]])

In [144]:
a5.reshape(4,-121)

array([[-0.31564177, -1.40582767],
       [ 0.1290978 ,  2.59538928],
       [-0.25646788, -1.45501661],
       [-1.79622745, -1.28522373]])

In [145]:
a5.reshape(-1,2)
# Vice versa also works

array([[-0.31564177, -1.40582767],
       [ 0.1290978 ,  2.59538928],
       [-0.25646788, -1.45501661],
       [-1.79622745, -1.28522373]])

In [146]:
a5.reshape(2,2,2)

array([[[-0.31564177, -1.40582767],
        [ 0.1290978 ,  2.59538928]],

       [[-0.25646788, -1.45501661],
        [-1.79622745, -1.28522373]]])

In [147]:
a1

array(['1', '43', '62', 'naren', '23.43', '@', 'True'], dtype='<U32')

In [148]:
a1[0]

'1'

In [149]:
a1[2:6]

array(['62', 'naren', '23.43', '@'], dtype='<U32')

In [150]:
a1[2:6:2]

array(['62', '23.43'], dtype='<U32')

In [151]:
a1[::-1]

array(['True', '@', '23.43', 'naren', '62', '43', '1'], dtype='<U32')

In [152]:
a2

array([[3, 5, 1, 3],
       [1, 6, 7, 2]])

In [153]:
a2[0]

array([3, 5, 1, 3])

In [154]:
a2[:,2:4]

array([[1, 3],
       [7, 2]])

In [155]:
a2[:,2:]

array([[1, 3],
       [7, 2]])

In [156]:
a2[:,[2,3]]

array([[1, 3],
       [7, 2]])

In [157]:
a2[[0,1],2:]

array([[1, 3],
       [7, 2]])

In [158]:
a6 = np.random.randint(2,90,(6,5))

In [159]:
a6

array([[65, 60, 29, 21, 14],
       [51, 28,  5,  2,  2],
       [15, 80, 57, 36, 28],
       [25,  4, 71,  8, 82],
       [87,  9, 80, 15, 57],
       [71, 56, 48, 59, 57]])

In [160]:
a6[a6>40]

array([65, 60, 51, 80, 57, 71, 82, 87, 80, 57, 71, 56, 48, 59, 57])

In [161]:
a6

array([[65, 60, 29, 21, 14],
       [51, 28,  5,  2,  2],
       [15, 80, 57, 36, 28],
       [25,  4, 71,  8, 82],
       [87,  9, 80, 15, 57],
       [71, 56, 48, 59, 57]])

In [162]:
a6[0][1] = 120

In [163]:
a6

array([[ 65, 120,  29,  21,  14],
       [ 51,  28,   5,   2,   2],
       [ 15,  80,  57,  36,  28],
       [ 25,   4,  71,   8,  82],
       [ 87,   9,  80,  15,  57],
       [ 71,  56,  48,  59,  57]])

In [164]:
a6[0,1]

120

In [165]:
a6[0,1]= 21

In [166]:
a6

array([[65, 21, 29, 21, 14],
       [51, 28,  5,  2,  2],
       [15, 80, 57, 36, 28],
       [25,  4, 71,  8, 82],
       [87,  9, 80, 15, 57],
       [71, 56, 48, 59, 57]])

In [167]:
a7 = np.random.randint(1,10,(3,3))
a8 = np.random.randint(1,10,(3,3))

In [168]:
a7

array([[9, 3, 2],
       [8, 8, 6],
       [5, 5, 8]])

In [169]:
a8

array([[8, 6, 2],
       [1, 4, 7],
       [5, 8, 5]])

In [170]:
a7*a8
# Not an matrix multiplication
# just element wise multiplication

array([[72, 18,  4],
       [ 8, 32, 42],
       [25, 40, 40]])

In [171]:
a7@a8
# gives matrix multiplication

array([[ 85,  82,  49],
       [102, 128, 102],
       [ 85, 114,  85]])

In [172]:
a7+100

array([[109, 103, 102],
       [108, 108, 106],
       [105, 105, 108]])

In [173]:
a7*2

array([[18,  6,  4],
       [16, 16, 12],
       [10, 10, 16]])

In [174]:
a7/0

C:\Users\naren\AppData\Local\Temp\ipykernel_11092\2765990889.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a7/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [175]:
a7**2
# a7 square

array([[81,  9,  4],
       [64, 64, 36],
       [25, 25, 64]], dtype=int32)

In [176]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [177]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [178]:
a9 = np.ones((3,3))

In [179]:
a9+10

array([[11., 11., 11.],
       [11., 11., 11.],
       [11., 11., 11.]])

In [180]:
a9 + np.array([1,2,3])
# This is called broadcasting array

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

In [181]:
# a9 + np.array([1,2])
#error

In [182]:
#a9 + np.array([1,2,3,4])
# Error

In [183]:
np.array([1,2,3,4]).T

array([1, 2, 3, 4])

In [184]:
np.array([[3,4,5]]).T + a9
# First transpose and the addition to get column wise addition

array([[4., 4., 4.],
       [5., 5., 5.],
       [6., 6., 6.]])

In [185]:
a7

array([[9, 3, 2],
       [8, 8, 6],
       [5, 5, 8]])

In [186]:
np.sqrt(a7)

array([[3.        , 1.73205081, 1.41421356],
       [2.82842712, 2.82842712, 2.44948974],
       [2.23606798, 2.23606798, 2.82842712]])

In [187]:
np.exp(a7)

array([[8.10308393e+03, 2.00855369e+01, 7.38905610e+00],
       [2.98095799e+03, 2.98095799e+03, 4.03428793e+02],
       [1.48413159e+02, 1.48413159e+02, 2.98095799e+03]])

In [188]:
np.log10(a7)

array([[0.95424251, 0.47712125, 0.30103   ],
       [0.90308999, 0.90308999, 0.77815125],
       [0.69897   , 0.69897   , 0.90308999]])

In [189]:
np.log(a7)

array([[2.19722458, 1.09861229, 0.69314718],
       [2.07944154, 2.07944154, 1.79175947],
       [1.60943791, 1.60943791, 2.07944154]])

In [190]:
np.log2(a7)

array([[3.169925  , 1.5849625 , 1.        ],
       [3.        , 3.        , 2.5849625 ],
       [2.32192809, 2.32192809, 3.        ]])

In [191]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [192]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [193]:
np.arange(0,10,2.5)

array([0. , 2.5, 5. , 7.5])

In [194]:
np.linspace(2,3, num = 50, retstep=True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 0.02040816326530612)

In [195]:
np.logspace(2,4, num = 4, base = 10)

array([  100.        ,   464.15888336,  2154.43469003, 10000.        ])

In [196]:
np.eye(5)
#Identiy matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## cufflinks
## seaborn

In [197]:
pip install cufflinks

In [198]:
import cufflinks as cf
import pandas as pd
import seaborn as sns

In [199]:
cf.go_offline()

In [200]:
df = pd.DataFrame(np.random.randn(100,3),columns = ['A','B','C'])

In [201]:
df.head()

A         B         C
0  0.879345  0.720610  1.617065
1  0.091057 -0.212031  0.519899
2  1.495787 -0.585246 -1.324377
3 -0.644405  0.537793  0.394607
4 -0.098466 -1.418561  0.590522

In [202]:
df.shape

(100, 3)

In [203]:
df.iplot()

In [204]:
df1 = pd.DataFrame(np.random.randint(3,100,(100,1)),columns = ['Z'])
df.head()

A         B         C
0  0.879345  0.720610  1.617065
1  0.091057 -0.212031  0.519899
2  1.495787 -0.585246 -1.324377
3 -0.644405  0.537793  0.394607
4 -0.098466 -1.418561  0.590522

In [205]:
df1.iplot()

In [206]:
df.iplot(x = 'A', y = 'B')

In [207]:
df.iplot(x = 'A', y = 'B',mode='markers')

In [208]:
df2 = sns.load_dataset('titanic')
df2.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [209]:
df2.iplot(x ="age",y='fare',mode='markers')
# to find correlation b/w age and fare
# there is no relation b/w age and fare

In [210]:
df2.iplot(x ="age",y='pclass',mode='markers')
# No correlation b/w age and pclass

In [211]:
df2.iplot(x ="fare",y='pclass',mode='markers')

In [216]:
df2.iplot(kind = 'bar', x = 'sex', y ='survived')
